server:
  port: 8083
  servlet:
    context-path: /springai
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${POLO_AI_API_KEY}
      base-url: ${POLO_AI_BASE_URL}
      chat:
        options:
          model: ${POLO_AI_CHAT_MODEL}
          temperature: 1.0
          max_completion_tokens: 2000
      image:
        options:
          model: ${POLO_AI_IMAGE_MODEL}
          quality: hd
