server:
  port: 8081
  servlet:
    context-path: /springai
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        enabled: true # By default its true, this triggers the autoconfiguration.
        options:
          model: ${OPENAI_CHAT_MODEL}
          temperature: 1.0
          max_completion_tokens: 2000
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}
    vectorstore:
      pgvector:
        initialize-schema: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/docs
    username: admin
    password: password
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
      validationQuery: SELECT 1

  flyway:
    enabled: false
ingestion:
  enabled: true